<?php
namespace frontend\controllers;

use common\models\Shop;
use erp\helper\HtmlHelper;
use frontend\models\OfficialModel;
use yii\web\Controller;

/**
 * Site controller
 */
class MapController extends Controller
{
    public $layout=false;
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionMapMark(){
        return $this->render('map');
    }

    public function actionGetShop(){
        $data = \Yii::$app->db->createCommand("select latitude,lontitude,name from mm_shop order by id desc limit 1000")->queryAll();
        foreach ($data as $k=>$v){
            if ( $v['lontitude'] == '' || $v['latitude'] == ''){
                unset($data[$k]);
            }
        }
        echo json_encode($data);
        exit;
    }

}
