<?php
/**
 * 显示推送信息
 * Tile:显示推送信息
 * Date: 2016/5/4
 * Time: 14:53
 */

namespace frontend\controllers;
use frontend\models\MessageModel;
use yii\web\Controller;
use Yii;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use linslin\yii2\curl;

class MessageController extends Controller
{
    private $_show_param;
    public $enableCsrfValidation = false;
    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function beforeAction($action) {
        $this->_show_param['columnKey'] = strtoupper ( Yii::$app->controller->id . '_' . $action->id );
        $this->_show_param['actionUrl'] = Yii::$app->homeUrl.Yii::$app->controller->id . '/' . $action->id;
        $this->_show_param['actionId'] =  Yii::$app->controller->id.'_'.$action->id;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    public function actionIndex() {
        Yii::$app->end();
    }
    public $layout = false;
    //显示推送信息
    public function actionMessage(){
        $id=Yii::$app->request->get('id',0);
        $mid=Yii::$app->request->get('mid',0);
        $messageid=Yii::$app->request->get('messageid',0);
        if($id && is_numeric($id) && $id>0){
            $model = new MessageModel();
            $this->_show_param['parameter']=$model->messageList($id,$mid,$messageid);
            return $this->render(Yii::$app->controller->action->id, ['show_param'=>$this->_show_param]);
        }else{
            return $this->render(Yii::$app->controller->action->id);
        }
    }
}