<?php
/**
 * 显示推送信息
 * Tile:显示推送信息
 * Date: 2016/5/4
 * Time: 14:53
 */

namespace frontend\controllers;
use frontend\models\PersonnelModel;
use yii\web\Controller;
use Yii;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\filters\CHttpCookie;
use linslin\yii2\curl;

class PersonnelController extends Controller
{
    private $_show_param;
    public $enableCsrfValidation = false;
    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public $layout = false;
    public function beforeAction($action) {
        $this->_show_param['columnKey'] = strtoupper ( Yii::$app->controller->id . '_' . $action->id );
        $this->_show_param['actionUrl'] = Yii::$app->homeUrl.Yii::$app->controller->id . '/' . $action->id;
        $this->_show_param['actionId'] =  Yii::$app->controller->id.'_'.$action->id;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    public function actionIndex() {
        $view = $this->action->id;
        return $this->render($view, ['show_param' => $this->_show_param]);
    }

    /**
     * 注册
     */
    public function actionRegist(){
       @extract($this->_show_param);
        $model = new PersonnelModel();
        if($_POST){
            $regist=$model->registEdit();
            return  $this->redirect(['personnel/perint','regist'=>$regist]);
        }
        return $this->render($this->action->id, ['show_param' => $this->_show_param]);
    }
    /**
     * 注册成功-或失败
     */
    public function actionPerint(){
        $this->_show_param['regist'] = \Yii::$app->request->get('regist');  //用户信息
        return $this->render($view = $this->action->id , ['show_param' => $this->_show_param]);
    }
    /**
     * 登录
     */
    public function actionLogin(){
        @extract($this->_show_param);
        $model = new PersonnelModel();
        if($_POST){
            $login=$model->login();
            if($login==2){
                return \Yii::$app->runAction('personnel/index');
            }else{
                return  $this->redirect(['personnel/success','user'=>$login]);
            }
        }
        return $this->render($this->action->id, ['show_param' => $this->_show_param]);
    }

    /**
     * 问卷
     */
    public function actionSuccess(){
        $model = new PersonnelModel();
        $this->_show_param['titleList']=$model->votoList();//标题信息
        $id=$this->_show_param['titleList'][0]['id'];//标题id
        $this->_show_param['tiankongList']=$model->tiankongList($id);//填空题信息
        $this->_show_param['wendaList']=$model->wendaList($id);//问答题信息
        $this->_show_param['userList'] = \Yii::$app->request->get('user');  //用户信息
        $this->_show_param['vidList'] = $id;
        return $this->render($view = $this->action->id , ['show_param' => $this->_show_param]);
    }

    /**
     * 答卷
     */
    public function actionAnswer(){
        $model = new PersonnelModel();
        $login=$model->answer();
        $this->_show_param['error']=$login;
        return $this->render($view = $this->action->id , ['show_param' => $this->_show_param]);
    }
}