<?php
namespace frontend\controllers;

use vendor\helpers\HtmlHelper;
use Yii;
use yii\helpers\Url;
use yii\web\Controller;
use frontend\models\OfficialModel;



/**
 * Site controller
 */
class SiteWapController extends Controller
{
    public $layout = 'wap-main.php';
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [];
    }

    public function beforeAction($action)
    {
        if(!HtmlHelper::isMobileDevice()){
            $this->redirect(Url::toRoute('site/'.$this->action->id));
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 官网首页
     * Tianbao KANG 2016-12-20
     * @return mixed
     */
    public function actionIndex()
    {
        $model = new OfficialModel();
        $show_param['articleList'] = $model->getArticlesList();
        $show_param['picList'] = $model->getIndexPicList();
        return $this->render($this->action->id,['show_param'=>$show_param]);
    }

    /**
     * 普通版页面
     * User: Tianbao KANG 2016-12-21
     */
    public function actionSdjApp()
    {
        return $this->render($this->action->id);
    }

    /**
     * 商家版
     * User: Tianbao KANG 2016-12-21
     */
    public function actionSellerApp()
    {
        return $this->render($this->action->id);
    }

    /**
     * 关于我们
     * User: Tianbao KANG 2016-12-21
     */
    public function actionAbout()
    {
        return $this->render($this->action->id);
    }

    /**
     * 关于我们-文化
     * User: Tianbao KANG 2016-12-21
     */
    public function actionAboutCulture()
    {
        $model = new OfficialModel();
        $show_param['cultureVideoList'] = $model->getCultureVideoList();
        $show_param['cultureArticleList'] = $model->getCultureArticelList();
        return $this->render($this->action->id,['show_param'=>$show_param]);
    }

    /**
     * 关于我们-新闻
     * User: Tianbao KANG 2016-12-21
     */
    public function actionAboutNews()
    {
        $model = new OfficialModel();
        $show_param['newsVideoList'] = $model->getNewsVideoList();
        $show_param['cnewsArticleList'] = $model->gecNewsArticelList();
        $show_param['lnewsArticleList'] = $model->gelNewsArticelList();
        return $this->render($this->action->id,['show_param'=>$show_param]);
    }

    /**
     * 关于我们-反馈
     * User: Tianbao KANG 2016-12-21
     */
    public function actionAboutFeedback()
    {
        $show_param['actionUrl'] = \Yii::$app->homeUrl . \Yii::$app->controller->id . '/' . $this->action->id;
        if($_POST){
            $data = \Yii::$app->request->post();
            if(!HtmlHelper::isMobile($data['mobile'])){
                echo '<script>alert("请输入正确手机号!");</script>';
                return $this->render($this->action->id,['show_param'=>$show_param]);
            }elseif(!$data['content']){
                echo '<script>alert("请填写反馈内容,谢谢!");</script>';
                return $this->render($this->action->id,['show_param'=>$show_param]);
            }
            $model = new OfficialModel();
            $res = $model->getFeedback($data);
            if($res){
                echo '<script>alert("非常感谢您的反馈!");</script>';
                return $this->render($this->action->id,['show_param'=>$show_param]);
            }else{
                echo '<script>alert("数据有误,请稍候重试!");</script>';
                return $this->render($this->action->id,['show_param'=>$show_param]);
            }

        }
        return $this->render($this->action->id,['show_param'=>$show_param]);
    }

    /**
     * 官网文章展示
     * User: Tianbao KANG 2016-12-20
     */
    public function actionArticlesShow(){
        $this->layout = false;
        $id = Yii::$app->request->get('id',0);

        $model = new OfficialModel();
        $article = $model->getArticleByID($id);

        return $this->render('articles-show',['article'=>$article]);
    }
    /**
     * 加入我们
     * User: Tianbao KANG 2-16-12-23
     */
    public function actionInsert(){
        return $this->render($this->action->id);
    }




}
